name: Feature Request
description: Suggest an idea.
title: "[FR]: "
labels: ["enhancement"]
assignees:
  - zsliu98
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a feature request!
  - type: textarea
    id: reason
    attributes:
      label: Why?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      render: markdown
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: What do you want?
      description: A clear and concise description of what you want to happen.
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ZL-Audio/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the Code of Conduct.
          required: true
